/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.vue;

import graphe.Cercle;
import java.awt.Color;
import static java.awt.geom.Point2D.distance;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import modele.Graphe;
import modele.Lien;
import modele.Sommet;
import sae.vue.PanneauDessin;


/**
 *
 * @author chris
 */
public class Fenetre extends javax.swing.JFrame {
    DefaultListModel<String> listModelListMaternite = new DefaultListModel<>();
    DefaultListModel<String> listModelListNutrition = new DefaultListModel<>();
    DefaultListModel<String> listModelListOperation = new DefaultListModel<>();
    DefaultListModel<String> listModelListVoisin = new DefaultListModel<>();
    DefaultListModel<String> listModelListChemin = new DefaultListModel<>();
    DefaultListModel<String> listModelListTrajetRisque = new DefaultListModel<>();
    
    private JPanel jPanneauDessin;
    private static Graphe graphe;
    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        graphe = new Graphe();
        initComponents();
        setSize(1400, 800);
        ouvrirMessageInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogListerNoeud = new javax.swing.JDialog();
        jRadioButtonTous = new javax.swing.JRadioButton();
        jRadioButtonTypeDonne = new javax.swing.JRadioButton();
        jLabelNbrNoeud = new javax.swing.JLabel();
        jLabelNbrTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMaternite = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNutrition = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOperatoire = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListChoixType = new javax.swing.JList<>();
        jButtonQuitter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNbrMaternite = new javax.swing.JLabel();
        jLabelNbrNutrition = new javax.swing.JLabel();
        jLabelNbrOperatoire = new javax.swing.JLabel();
        jButtonListerOk = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogVoisinage = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListCentreVoisin = new javax.swing.JList<>();
        jRadioButtonDistance1 = new javax.swing.JRadioButton();
        jRadioButtonDistance2 = new javax.swing.JRadioButton();
        jButtonOkVoisin = new javax.swing.JButton();
        jButtonQuitterVoisin = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButtonVoisinageTous = new javax.swing.JRadioButton();
        jRadioButtonVoisinageM = new javax.swing.JRadioButton();
        jRadioButtonVoisinageN = new javax.swing.JRadioButton();
        jRadioButtonVoisinageO = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldVoisinageNbr = new javax.swing.JTextField();
        jComboBoxVoisinage = new javax.swing.JComboBox<>();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialogComparateur = new javax.swing.JDialog();
        jButtonQuitterComparateur = new javax.swing.JButton();
        jButtonOkComparateur = new javax.swing.JButton();
        jComboBoxCentre1 = new javax.swing.JComboBox<>();
        jComboBoxCentre2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelNbM1 = new javax.swing.JLabel();
        jLabelNbN1 = new javax.swing.JLabel();
        jLabelNbO1 = new javax.swing.JLabel();
        jLabelNbM2 = new javax.swing.JLabel();
        jLabelNbN2 = new javax.swing.JLabel();
        jLabelNbO2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxOption = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jDialogModifierLien = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldFiabilite = new javax.swing.JTextField();
        jTextFieldDistance = new javax.swing.JTextField();
        jTextFieldDuree = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButtonConfirmerChangement = new javax.swing.JButton();
        jButtonCentre1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBoxModifier1 = new javax.swing.JComboBox<>();
        jComboBoxModifier2 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jButtonModifierOk = new javax.swing.JButton();
        jButtonModifierQuitter = new javax.swing.JButton();
        jDialogChemin = new javax.swing.JDialog();
        jComboBoxChoix = new javax.swing.JComboBox<>();
        jComboBoxChemin1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBoxChemin2 = new javax.swing.JComboBox<>();
        jButtonCheminOk = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListChemin = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jButtonCheminQuitter = new javax.swing.JButton();
        jDialogRisque = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldTrajetFiabilite = new javax.swing.JTextField();
        jButtonTrajetOk = new javax.swing.JButton();
        jButtonTrajetQuitter = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListTrajet = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCharger = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemListerNoeud = new javax.swing.JMenuItem();
        jMenuItemAfficherVoisinage = new javax.swing.JMenuItem();
        jMenuItemComparateur = new javax.swing.JMenuItem();
        jMenuItemModifierLien = new javax.swing.JMenuItem();
        jMenuItemChemin = new javax.swing.JMenuItem();
        jMenuTrajet = new javax.swing.JMenuItem();

        jDialogListerNoeud.setTitle("Lister tous les centres");

        buttonGroup1.add(jRadioButtonTous);
        jRadioButtonTous.setText("Lister tous les centres (regroupés par catégories)");
        jRadioButtonTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTousActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonTypeDonne);
        jRadioButtonTypeDonne.setText("Lister centres par type donné");
        jRadioButtonTypeDonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTypeDonneActionPerformed(evt);
            }
        });

        jLabelNbrNoeud.setText("Nombre de centre total :");

        jLabel1.setText("Maternité :");

        jLabel2.setText("Nutrition :");

        jLabel3.setText("Opératoire :");

        jListMaternite.setEnabled(false);
        jScrollPane1.setViewportView(jListMaternite);

        jListNutrition.setEnabled(false);
        jScrollPane2.setViewportView(jListNutrition);

        jListOperatoire.setEnabled(false);
        jScrollPane3.setViewportView(jListOperatoire);

        jListChoixType.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Maternité", "Nutrition", "Opération" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListChoixType.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(jListChoixType);

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre :");

        jLabel5.setText("Nombre :");

        jLabel6.setText("Nombre :");

        jButtonListerOk.setText("Ok");
        jButtonListerOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListerOkActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 0));
        jLabel34.setText("Liste de tous les noeuds ");

        javax.swing.GroupLayout jDialogListerNoeudLayout = new javax.swing.GroupLayout(jDialogListerNoeud.getContentPane());
        jDialogListerNoeud.getContentPane().setLayout(jDialogListerNoeudLayout);
        jDialogListerNoeudLayout.setHorizontalGroup(
            jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jButtonQuitter))
                            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                        .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelNbrMaternite, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(36, 36, 36)
                                        .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelNbrNutrition, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(40, 40, 40)
                                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNbrOperatoire))))
                            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                        .addComponent(jLabelNbrNoeud, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelNbrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButtonTous, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonListerOk, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButtonTypeDonne, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel34)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jDialogListerNoeudLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        jDialogListerNoeudLayout.setVerticalGroup(
            jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTous)
                    .addComponent(jRadioButtonTypeDonne))
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogListerNoeudLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonListerOk))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabelNbrNutrition))
                    .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabelNbrOperatoire))
                    .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabelNbrMaternite, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jDialogListerNoeudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogListerNoeudLayout.createSequentialGroup()
                        .addComponent(jLabelNbrNoeud)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonQuitter))
                    .addComponent(jLabelNbrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jDialogListerNoeudLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        jDialogVoisinage.setTitle("Voisinage");

        jLabel7.setText("Distance :");

        jLabel8.setText("Centre :");

        jListCentreVoisin.setEnabled(false);
        jScrollPane7.setViewportView(jListCentreVoisin);

        buttonGroup2.add(jRadioButtonDistance1);
        jRadioButtonDistance1.setText("1 - Distance");

        buttonGroup2.add(jRadioButtonDistance2);
        jRadioButtonDistance2.setText("2 - Distance");

        jButtonOkVoisin.setText("Ok");
        jButtonOkVoisin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkVoisinActionPerformed(evt);
            }
        });

        jButtonQuitterVoisin.setText("Quitter");
        jButtonQuitterVoisin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterVoisinActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Voisinage");

        jLabel36.setText("Filtre :");

        buttonGroup3.add(jRadioButtonVoisinageTous);
        jRadioButtonVoisinageTous.setText("Tous");

        buttonGroup3.add(jRadioButtonVoisinageM);
        jRadioButtonVoisinageM.setText("Maternité");

        buttonGroup3.add(jRadioButtonVoisinageN);
        jRadioButtonVoisinageN.setText("Nutrition");

        buttonGroup3.add(jRadioButtonVoisinageO);
        jRadioButtonVoisinageO.setText("Opératoire");

        jLabel37.setText("Nombre : ");

        jTextFieldVoisinageNbr.setEnabled(false);

        javax.swing.GroupLayout jDialogVoisinageLayout = new javax.swing.GroupLayout(jDialogVoisinage.getContentPane());
        jDialogVoisinage.getContentPane().setLayout(jDialogVoisinageLayout);
        jDialogVoisinageLayout.setHorizontalGroup(
            jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel35))
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonVoisinageTous)
                                    .addComponent(jRadioButtonVoisinageM)))
                            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxVoisinage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonOkVoisin)
                                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel36))))))
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDistance1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonDistance2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldVoisinageNbr, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonVoisinageN)
                            .addComponent(jRadioButtonVoisinageO)))
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButtonQuitterVoisin)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jDialogVoisinageLayout.setVerticalGroup(
            jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldVoisinageNbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogVoisinageLayout.createSequentialGroup()
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel36))
                                    .addComponent(jComboBoxVoisinage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonDistance1)
                                    .addComponent(jRadioButtonVoisinageTous))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDistance2)
                                    .addComponent(jRadioButtonVoisinageM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonVoisinageN))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonVoisinageO)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonOkVoisin)
                        .addGap(47, 47, 47)
                        .addGroup(jDialogVoisinageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonQuitterVoisin)
                .addGap(30, 30, 30))
        );

        jDialogComparateur.setTitle("Comparateur");

        jButtonQuitterComparateur.setText("Quitter");
        jButtonQuitterComparateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterComparateurActionPerformed(evt);
            }
        });

        jButtonOkComparateur.setText("Ok");
        jButtonOkComparateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkComparateurActionPerformed(evt);
            }
        });

        jLabel12.setText("Centre 1 : ");

        jLabel13.setText("Centre 2 : ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setText("Nombre de matérnité  :");

        jLabel15.setText("Nombre de centre de nutrition  :");

        jLabel16.setText("Nombre de bloc opératoire  :");

        jLabel18.setText("Option : ");

        jComboBoxOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de centre à 2-distance et moins", "Nombre de centre à plus de 2-distance" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Comparateur");

        javax.swing.GroupLayout jDialogComparateurLayout = new javax.swing.GroupLayout(jDialogComparateur.getContentPane());
        jDialogComparateur.getContentPane().setLayout(jDialogComparateurLayout);
        jDialogComparateurLayout.setHorizontalGroup(
            jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogComparateurLayout.createSequentialGroup()
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogComparateurLayout.createSequentialGroup()
                        .addContainerGap(191, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)
                        .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogComparateurLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNbN1)
                                    .addComponent(jLabelNbO1)
                                    .addComponent(jLabelNbM1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogComparateurLayout.createSequentialGroup()
                                .addComponent(jComboBoxCentre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel13)))
                        .addGap(36, 36, 36))
                    .addGroup(jDialogComparateurLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(337, 337, 337)))
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCentre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbM2)
                    .addComponent(jLabelNbN2)
                    .addComponent(jLabelNbO2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                        .addComponent(jButtonQuitterComparateur)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                        .addComponent(jButtonOkComparateur)
                        .addGap(292, 292, 292))))
            .addGroup(jDialogComparateurLayout.createSequentialGroup()
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogComparateurLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel18))
                    .addGroup(jDialogComparateurLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogComparateurLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelNbM1, jLabelNbM2, jLabelNbN1, jLabelNbN2, jLabelNbO1, jLabelNbO2});

        jDialogComparateurLayout.setVerticalGroup(
            jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogComparateurLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCentre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCentre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComparateurLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(66, 66, 66)))
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelNbM1)
                    .addComponent(jLabelNbM2))
                .addGap(63, 63, 63)
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabelNbN1)
                    .addComponent(jLabelNbN2))
                .addGap(70, 70, 70)
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabelNbO1)
                    .addComponent(jLabelNbO2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogComparateurLayout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jDialogComparateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBoxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonOkComparateur)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonQuitterComparateur)
                .addGap(103, 103, 103))
        );

        jDialogModifierLien.setTitle("Modifier caractéristiques d'un lien");

        jLabel19.setText("Centre 1 :");

        jLabel21.setText("Fiabilité :");

        jLabel22.setText("Distance :");

        jLabel23.setText("Durée :");

        jButtonConfirmerChangement.setText("Effectuer les changements");
        jButtonConfirmerChangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerChangementActionPerformed(evt);
            }
        });

        jButtonCentre1.setText("Centre 1 saisie");
        jButtonCentre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCentre1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Centre 2 :");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("Modifier les caractéristiques d'un lien");

        jLabel31.setText("Caractéristiques :");

        jButtonModifierOk.setText("Ok");
        jButtonModifierOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierOkActionPerformed(evt);
            }
        });

        jButtonModifierQuitter.setText("Quitter");
        jButtonModifierQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogModifierLienLayout = new javax.swing.GroupLayout(jDialogModifierLien.getContentPane());
        jDialogModifierLien.getContentPane().setLayout(jDialogModifierLienLayout);
        jDialogModifierLienLayout.setHorizontalGroup(
            jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFiabilite, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonConfirmerChangement)))
                    .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButtonModifierOk))
                    .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButtonModifierQuitter))
                    .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel29)
                        .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                            .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24)))
                                .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(jLabel31)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                                    .addComponent(jComboBoxModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(jButtonCentre1))
                                .addComponent(jComboBoxModifier2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jDialogModifierLienLayout.setVerticalGroup(
            jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogModifierLienLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel29)
                .addGap(44, 44, 44)
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBoxModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCentre1))
                .addGap(33, 33, 33)
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxModifier2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(43, 43, 43)
                .addComponent(jButtonModifierOk)
                .addGap(21, 21, 21)
                .addComponent(jLabel31)
                .addGap(17, 17, 17)
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldFiabilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialogModifierLienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFieldDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonConfirmerChangement)
                .addGap(68, 68, 68)
                .addComponent(jButtonModifierQuitter)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jDialogChemin.setTitle("Trouver chemin");

        jComboBoxChoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chemin le plus fiable", "Chemin le plus court en distance", "Chemin le plus court en durée" }));

        jLabel25.setText("Centre 1 :");

        jLabel26.setText("Centre 2 :");

        jButtonCheminOk.setText("Ok");
        jButtonCheminOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheminOkActionPerformed(evt);
            }
        });

        jLabel27.setText("Choix :");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("Trouver un chemin entre deux centres ");

        jListChemin.setEnabled(false);
        jScrollPane8.setViewportView(jListChemin);

        jLabel30.setText("Chemin :");

        jButtonCheminQuitter.setText("Quitter");
        jButtonCheminQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheminQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogCheminLayout = new javax.swing.GroupLayout(jDialogChemin.getContentPane());
        jDialogChemin.getContentPane().setLayout(jDialogCheminLayout);
        jDialogCheminLayout.setHorizontalGroup(
            jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheminLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogCheminLayout.createSequentialGroup()
                        .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jDialogCheminLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxChemin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogCheminLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jDialogCheminLayout.createSequentialGroup()
                        .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(34, 34, 34)
                        .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogCheminLayout.createSequentialGroup()
                                .addComponent(jButtonCheminOk)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDialogCheminLayout.createSequentialGroup()
                                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxChemin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jDialogCheminLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButtonCheminQuitter)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogCheminLayout.setVerticalGroup(
            jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCheminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel28)
                .addGap(28, 28, 28)
                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChemin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(30, 30, 30)
                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxChemin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jDialogCheminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxChoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(33, 33, 33)
                .addComponent(jButtonCheminOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonCheminQuitter)
                .addGap(37, 37, 37))
        );

        jDialogRisque.setTitle("Trajet risqué");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Trajet risqué");

        jLabel32.setText("Fiabilité (max 100) :");

        jButtonTrajetOk.setText("Ok");
        jButtonTrajetOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrajetOkActionPerformed(evt);
            }
        });

        jButtonTrajetQuitter.setText("Quitter");
        jButtonTrajetQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrajetQuitterActionPerformed(evt);
            }
        });

        jListTrajet.setToolTipText("");
        jListTrajet.setEnabled(false);
        jScrollPane5.setViewportView(jListTrajet);

        jLabel33.setText("Trajet risqué (supérieur ou égal à la fiabilité donné) :");

        javax.swing.GroupLayout jDialogRisqueLayout = new javax.swing.GroupLayout(jDialogRisque.getContentPane());
        jDialogRisque.getContentPane().setLayout(jDialogRisqueLayout);
        jDialogRisqueLayout.setHorizontalGroup(
            jDialogRisqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRisqueLayout.createSequentialGroup()
                .addGroup(jDialogRisqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogRisqueLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel20))
                    .addGroup(jDialogRisqueLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel32)
                        .addGap(40, 40, 40)
                        .addComponent(jTextFieldTrajetFiabilite, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonTrajetOk))
                    .addGroup(jDialogRisqueLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButtonTrajetQuitter))
                    .addGroup(jDialogRisqueLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogRisqueLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel33)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jDialogRisqueLayout.setVerticalGroup(
            jDialogRisqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogRisqueLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel20)
                .addGap(49, 49, 49)
                .addGroup(jDialogRisqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldTrajetFiabilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrajetOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jButtonTrajetQuitter)
                .addGap(71, 71, 71))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenuCharger.setText("Charger un fichier");
        jMenuCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuChargerActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCharger);
        jMenu1.add(jSeparator2);

        jMenuItemListerNoeud.setText("Lister centre");
        jMenuItemListerNoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListerNoeudActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemListerNoeud);

        jMenuItemAfficherVoisinage.setText("Afficher voisinage");
        jMenuItemAfficherVoisinage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAfficherVoisinageActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAfficherVoisinage);

        jMenuItemComparateur.setText("Comparateur");
        jMenuItemComparateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComparateurActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemComparateur);

        jMenuItemModifierLien.setText("Modifier un lien");
        jMenuItemModifierLien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModifierLienActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemModifierLien);

        jMenuItemChemin.setText("Trouver chemin");
        jMenuItemChemin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheminActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemChemin);

        jMenuTrajet.setText("Trajet risqués");
        jMenuTrajet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrajetActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuTrajet);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListerNoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListerNoeudActionPerformed
        // Bouton menu afficher noeuds
       jDialogListerNoeud.setSize(600,750);
       jDialogListerNoeud.setLocationRelativeTo(null);
       effacerDonneeLister();
       jListChoixType.setEnabled(false);
       jButtonListerOk.setEnabled(false);
       buttonGroup1.clearSelection();
       jDialogListerNoeud.setVisible(true);
    }//GEN-LAST:event_jMenuItemListerNoeudActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // boutton quitter
        jDialogListerNoeud.setVisible(false);
        
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jRadioButtonTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTousActionPerformed
        // Bouton afficher tous les centres
        effacerDonneeLister();
        jListChoixType.setEnabled(false);
        jButtonListerOk.setEnabled(false);
        jListMaternite.setModel(listModelListMaternite);
        jListNutrition.setModel(listModelListNutrition);
        jListOperatoire.setModel(listModelListOperation);
        
        for (Sommet sommet : graphe.getSommets().values()) {
            if (sommet.getType().equals("M")) {
                listModelListMaternite.addElement(sommet.getNom());
            } else if (sommet.getType().equals("N")) {
                listModelListNutrition.addElement(sommet.getNom());
            } else if (sommet.getType().equals("O")) {
                listModelListOperation.addElement(sommet.getNom());
            }
        }    
        jLabelNbrMaternite.setText(String.valueOf(listModelListMaternite.getSize()));
        jLabelNbrNutrition.setText(String.valueOf(listModelListNutrition.getSize()));
        jLabelNbrOperatoire.setText(String.valueOf(listModelListOperation.getSize()));
        jLabelNbrTotal.setText(String.valueOf(listModelListOperation.getSize()+listModelListNutrition.getSize()+listModelListMaternite.getSize()));
    
        
        
        
        
    }//GEN-LAST:event_jRadioButtonTousActionPerformed
    private void jMenuItemAfficherVoisinageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAfficherVoisinageActionPerformed
        // Bouton menu voisinage
        
       
       jTextFieldVoisinageNbr.setText("");
       listModelListVoisin.clear();
       buttonGroup2.clearSelection();
       buttonGroup3.clearSelection();
       
       
       
       for (Sommet sommet : graphe.getSommets().values()){
           jComboBoxVoisinage.addItem(sommet.getNom());
       }
       
       
       
       jDialogVoisinage.setSize(530,650);
       jDialogVoisinage.setLocationRelativeTo(this);
       jDialogVoisinage.setVisible(true);
       
    }//GEN-LAST:event_jMenuItemAfficherVoisinageActionPerformed

    private void jRadioButtonTypeDonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTypeDonneActionPerformed
        // Bouton Lister noeud par type donné
        
       effacerDonneeLister();
       jListChoixType.setEnabled(true);
       jButtonListerOk.setEnabled(true);
       
    }//GEN-LAST:event_jRadioButtonTypeDonneActionPerformed

    private void jMenuChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuChargerActionPerformed
        JFileChooser fileChooser = new JFileChooser();
       
       String repertoireCourant = System.getProperty("user.dir");
       fileChooser.setCurrentDirectory(new File(repertoireCourant));

       int result = fileChooser.showOpenDialog(this);

       if (result == JFileChooser.APPROVE_OPTION) {
           File selectedFile = fileChooser.getSelectedFile();
           String nomFichier = selectedFile.getAbsolutePath();

           if (nomFichier.endsWith(".csv")) {
               // Créer une nouvelle instance de Graphe
               graphe = new Graphe();
               // Charger le graphe à partir du fichier
               graphe.chargerGraphe(nomFichier);
               jPanneauDessin = new PanneauDessin(graphe);
               this.setContentPane(jPanneauDessin);

               // Mettre à jour la fenêtre
               revalidate();
               repaint();
               JOptionPane.showMessageDialog(this, "Le graphe a été chargé avec succès", "Status chargement", JOptionPane.INFORMATION_MESSAGE);
           } else {
               JOptionPane.showMessageDialog(this, "Le fichier sélectionné n'est pas un fichier CSV", "Erreur", JOptionPane.ERROR_MESSAGE);
           }
       } else if (result == JFileChooser.CANCEL_OPTION) {
           
       }
        
    }//GEN-LAST:event_jMenuChargerActionPerformed

    private void jButtonListerOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListerOkActionPerformed
        // TODO add your handling code here:
        effacerDonneeLister();
        jListMaternite.setModel(listModelListMaternite);
        jListNutrition.setModel(listModelListNutrition);
        jListOperatoire.setModel(listModelListOperation);
        
        if (!jListChoixType.isSelectionEmpty()){
            if (jListChoixType.getSelectedValue().equals("Maternité")) {
                for (Sommet sommet : graphe.getSommets().values()) {
                    if (sommet.getType().equals("M")) {
                        listModelListMaternite.addElement(sommet.getNom());
                    }
                }
            }   else if (jListChoixType.getSelectedValue().equals("Nutrition")){
                for (Sommet sommet : graphe.getSommets().values()) {
                    if (sommet.getType().equals("N")) {
                        listModelListNutrition.addElement(sommet.getNom());
                    }
                }

                }else if(jListChoixType.getSelectedValue().equals("Opération")) {
                    for (Sommet sommet : graphe.getSommets().values()) {
                    if (sommet.getType().equals("O")) {
                        listModelListOperation.addElement(sommet.getNom());
                    }
                }
            }
        }     

        jLabelNbrMaternite.setText(String.valueOf(listModelListMaternite.getSize()));
        jLabelNbrNutrition.setText(String.valueOf(listModelListNutrition.getSize()));
        jLabelNbrOperatoire.setText(String.valueOf(listModelListOperation.getSize()));
        jLabelNbrTotal.setText(String.valueOf(listModelListOperation.getSize()+listModelListNutrition.getSize()+listModelListMaternite.getSize()));
        
        
        
        
    }//GEN-LAST:event_jButtonListerOkActionPerformed

    private void jButtonQuitterVoisinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterVoisinActionPerformed
        // TODO add your handling code here:
        jDialogVoisinage.setVisible(false);
    }//GEN-LAST:event_jButtonQuitterVoisinActionPerformed

    private void jButtonOkVoisinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkVoisinActionPerformed
        // TODO add your handling code here:
        jTextFieldVoisinageNbr.setText("");
        jListCentreVoisin.setModel(listModelListVoisin);
        listModelListVoisin.clear();
        
        if (jRadioButtonDistance1.isSelected()){
            String selectedCenter = jComboBoxVoisinage.getSelectedItem().toString();
            List<Sommet> voisins = graphe.getVoisinDirect(selectedCenter); 
            if (jRadioButtonVoisinageTous.isSelected()){
                for (Sommet voisin : voisins) {
                    listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+") | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getFiabilite()*10 +"% | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDistance()+"km | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDureeMoyenne()+"min" );
                } 
            }else if (jRadioButtonVoisinageM.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("M"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+") | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getFiabilite()*10 +"% | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDistance()+"km | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDureeMoyenne()+"min" );
                }
            } else if (jRadioButtonVoisinageO.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("O"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+") | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getFiabilite()*10 +"% | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDistance()+"km | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDureeMoyenne()+"min" );
                }
            }else if (jRadioButtonVoisinageN.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("N"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+") | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getFiabilite()*10 +"% | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDistance()+"km | "+graphe.getLienEntreCentres(selectedCenter,voisin.getNom()).getDureeMoyenne()+"min" );
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aucun filtre selectionné", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            
        } else if (jRadioButtonDistance2.isSelected()){
            String selectedCenter = jComboBoxVoisinage.getSelectedItem().toString();
            List<Sommet> voisins = graphe.getVoisin2Distance(selectedCenter); 

            if (jRadioButtonVoisinageTous.isSelected()){
                for (Sommet voisin : voisins) {
                listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+")");
                } 
            }else if (jRadioButtonVoisinageM.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("M"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+")");
                }
            } else if (jRadioButtonVoisinageO.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("O"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+")");
                }
            }else if (jRadioButtonVoisinageN.isSelected()){
                for (Sommet voisin : voisins) {
                    if (voisin.getType().equals("N"))
                        listModelListVoisin.addElement(voisin.getNom()+" ("+voisin.getType()+")");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aucun filtre selectionné", "Erreur", JOptionPane.ERROR_MESSAGE);
            } 
        }else {
            JOptionPane.showMessageDialog(this, "Aucune distance selectionné", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextFieldVoisinageNbr.setText(String.valueOf(listModelListVoisin.getSize()));
        
    }//GEN-LAST:event_jButtonOkVoisinActionPerformed

    private void jMenuItemComparateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComparateurActionPerformed
        // TODO add your handling code here:
         effacerDonneeComparateur();
        jDialogComparateur.setSize(750,700);
        jDialogComparateur.setLocationRelativeTo(this);
        jDialogComparateur.setVisible(true);

       if (jComboBoxCentre1.getItemCount()!=0){
            jComboBoxCentre1.removeAllItems();
            jComboBoxCentre2.removeAllItems();
       }
        
        for (Sommet sommet : graphe.getSommets().values()) {
            jComboBoxCentre1.addItem(sommet.getNom());
            jComboBoxCentre2.addItem(sommet.getNom());
        }

       
       
    }//GEN-LAST:event_jMenuItemComparateurActionPerformed

    private void jButtonOkComparateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkComparateurActionPerformed
        // TODO add your handling code here:

        if (jComboBoxCentre1.getItemCount()!=0){
            if (jComboBoxOption.getSelectedIndex()==0){

                String s1 =  jComboBoxCentre1.getSelectedItem().toString();
                String s2 =  jComboBoxCentre2.getSelectedItem().toString();

                List<Sommet> nbM1 = graphe.getMaterniteMax2Distance(graphe.getCentreMax2Distance(s1));
                List<Sommet> nbO1 = graphe.getNutritionMax2Distance(graphe.getCentreMax2Distance(s1));
                List<Sommet> nbN1 = graphe.getOperatoireMax2Distance(graphe.getCentreMax2Distance(s1));

                List<Sommet> nbM2 = graphe.getMaterniteMax2Distance(graphe.getCentreMax2Distance(s2));
                List<Sommet> nbO2 = graphe.getNutritionMax2Distance(graphe.getCentreMax2Distance(s2));
                List<Sommet> nbN2 = graphe.getOperatoireMax2Distance(graphe.getCentreMax2Distance(s2));

                jLabelNbM1.setText(String.valueOf(nbM1.size()));
                jLabelNbN1.setText(String.valueOf(nbN1.size()));
                jLabelNbO1.setText(String.valueOf(nbO1.size()));

                jLabelNbM2.setText(String.valueOf(nbM2.size()));
                jLabelNbN2.setText(String.valueOf(nbN2.size()));
                jLabelNbO2.setText(String.valueOf(nbO2.size()));
            }else if (jComboBoxOption.getSelectedIndex()==1){
                String s1 =  jComboBoxCentre1.getSelectedItem().toString();
                String s2 =  jComboBoxCentre2.getSelectedItem().toString();

                List<Sommet> nbM1 = graphe.getMaterniteMax2Distance(graphe.getCentreMax2Distance(s1));
                List<Sommet> nbO1 = graphe.getNutritionMax2Distance(graphe.getCentreMax2Distance(s1));
                List<Sommet> nbN1 = graphe.getOperatoireMax2Distance(graphe.getCentreMax2Distance(s1));

                List<Sommet> nbM2 = graphe.getMaterniteMax2Distance(graphe.getCentreMax2Distance(s2));
                List<Sommet> nbO2 = graphe.getNutritionMax2Distance(graphe.getCentreMax2Distance(s2));
                List<Sommet> nbN2 = graphe.getOperatoireMax2Distance(graphe.getCentreMax2Distance(s2));

                jLabelNbM1.setText(String.valueOf(graphe.getNombreMaternite()-nbM1.size()));
                jLabelNbN1.setText(String.valueOf(graphe.getNombreNutrition()-nbN1.size()));
                jLabelNbO1.setText(String.valueOf(graphe.getNombreOperatoire()-nbO1.size()));

                jLabelNbM2.setText(String.valueOf(graphe.getNombreMaternite()-nbM2.size()));
                jLabelNbN2.setText(String.valueOf(graphe.getNombreNutrition()-nbN2.size()));
                jLabelNbO2.setText(String.valueOf(graphe.getNombreOperatoire()-nbO2.size()));

            }

        }else {
            JOptionPane.showMessageDialog(this, "Aucun graphe chargé", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOkComparateurActionPerformed

    private void jButtonQuitterComparateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterComparateurActionPerformed
        // TODO add your handling code here:
        jDialogComparateur.setVisible(false);
    }//GEN-LAST:event_jButtonQuitterComparateurActionPerformed

    private void jMenuItemModifierLienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModifierLienActionPerformed
        jTextFieldFiabilite.setEditable(false);
        jTextFieldDuree.setEditable(false);
        jTextFieldDistance.setEditable(false);
        
        jTextFieldFiabilite.setText("");
        jTextFieldDistance.setText("");
        jTextFieldDuree.setText("");
        
        if (jComboBoxModifier1.getItemCount()!=0){
            jComboBoxModifier1.removeAllItems();
        }
        if (jComboBoxModifier2.getItemCount()!=0){
            jComboBoxModifier2.removeAllItems();
        }
        for (Sommet sommet : graphe.getSommets().values()){
            jComboBoxModifier1.addItem(sommet.getNom());
        }
        
        jDialogModifierLien.setSize(400,650);
        jDialogModifierLien.setLocationRelativeTo(this);
        jDialogModifierLien.setVisible(true);
    }//GEN-LAST:event_jMenuItemModifierLienActionPerformed

    private void jButtonConfirmerChangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerChangementActionPerformed
        Sommet sommet1 = graphe.getSommets().get(jComboBoxModifier1.getSelectedItem().toString());
        Sommet sommet2 = graphe.getSommets().get(jComboBoxModifier2.getSelectedItem().toString());
        Lien lien = null;

        for (Lien l : graphe.getLiens()) { //Rechercher le lien sommet1/sommet2
            if ((l.getSommet1() == sommet1 && l.getSommet2() == sommet2) ||
                    (l.getSommet1() == sommet2 && l.getSommet2() == sommet1)) {
                lien = l;
                break;
            }
        }

        if (lien != null) {
            
            //Récuperer les infos des jTextField
            try {
                double duree = Double.parseDouble(jTextFieldDuree.getText());
                double distance = Double.parseDouble(jTextFieldDistance.getText());
                double fiabilite = Double.parseDouble(jTextFieldFiabilite.getText());
                //Mettre à jour le lien avec les nouvelles données
                if (fiabilite > 10) { //Parce que fiabilité de plus de 10 n'est pas autorisé
                    JOptionPane.showMessageDialog(jDialogModifierLien,"La fiabilité dois être compris entre 1 et 10 !");
                }else if (duree<0 ||distance<0||fiabilite<0){
                    JOptionPane.showMessageDialog(jDialogModifierLien,"Les valeurs doivent être positif !");
                            
                } else {
                    lien.setDureeMoyenne(duree);
                    lien.setDistance(distance);
                    lien.setFiabilite(fiabilite);
                    JOptionPane.showMessageDialog(jDialogModifierLien,"Les changements ont été pris en compte !");
                }
            } catch (NumberFormatException ex){
                        JOptionPane.showMessageDialog(this, "Les valeurs doivent être des doubles", "Erreur", JOptionPane.ERROR_MESSAGE);
                        }
            
        }
    }//GEN-LAST:event_jButtonConfirmerChangementActionPerformed

    private void jButtonCentre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCentre1ActionPerformed
        
        if (jComboBoxModifier1.getItemCount()!=0){
            if (jComboBoxModifier2.getItemCount()!=0){
                jComboBoxModifier2.removeAllItems();
            }
            String selectedCenter = jComboBoxModifier1.getSelectedItem().toString();
            List<Sommet> voisins = graphe.getVoisinDirect(selectedCenter);
            for (Sommet voisin : voisins) {
                    jComboBoxModifier2.addItem(voisin.getNom());
                }
        }
    }//GEN-LAST:event_jButtonCentre1ActionPerformed

    private void jMenuItemCheminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheminActionPerformed
        // menu chemin
        
        jListChemin.setModel(listModelListChemin);
        listModelListChemin.clear();
        jComboBoxChoix.setSelectedIndex(0);
        
        viderCheminCentre2();
        if (jComboBoxChemin1.getItemCount()!=0){
            jComboBoxChemin1.removeAllItems();
            jComboBoxChemin2.removeAllItems();
        }

        for (Sommet sommet : graphe.getSommets().values()){
            jComboBoxChemin1.addItem(sommet.getNom());
            jComboBoxChemin2.addItem(sommet.getNom());
            
        }
        
        
        
        jDialogChemin.setSize(450,700);
        jDialogChemin.setLocationRelativeTo(this);
        jDialogChemin.setVisible(true);
        
       
       
    }//GEN-LAST:event_jMenuItemCheminActionPerformed

    private void jButtonCheminQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheminQuitterActionPerformed
        // TODO add your handling code here:
        jDialogChemin.setVisible(false);
    }//GEN-LAST:event_jButtonCheminQuitterActionPerformed

    private void jButtonCheminOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheminOkActionPerformed
        // TODO add your handling code here:
        listModelListChemin.clear();
        if (jComboBoxChemin1.getItemCount()!=0){
            Sommet s1 = graphe.sommets.get(jComboBoxChemin1.getSelectedItem().toString());
            Sommet s2 = graphe.sommets.get(jComboBoxChemin2.getSelectedItem().toString());
            if (graphe.dijkstraDuree(s1, s2)!=null){
                if (jComboBoxChoix.getSelectedIndex()==0){
                List<Sommet> cheminPlusFiable = graphe.dijkstraFiabilite(s1, s2);
                for (Sommet sommet : cheminPlusFiable){
                    listModelListChemin.addElement("-> " +sommet.getNom());
                }
                }else if (jComboBoxChoix.getSelectedIndex()==1){

                    List<Sommet> cheminPlusCourtDistance = graphe.dijkstraDistance(s1, s2);
                    for (Sommet sommet : cheminPlusCourtDistance){
                        listModelListChemin.addElement("-> "+sommet.getNom());
                    }
                }else{

                    List<Sommet> cheminPlusCourtDuree = graphe.dijkstraDuree(s1, s2);
                    for (Sommet sommet : cheminPlusCourtDuree){
                        listModelListChemin.addElement("-> "+sommet.getNom());
                    }
                }
            }else {
                JOptionPane.showMessageDialog(this, "Ces centres ne sont pas reliés", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            
              
        }else {
            JOptionPane.showMessageDialog(this, "Aucun centre trouvé", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButtonCheminOkActionPerformed

    private void jButtonModifierOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierOkActionPerformed
        // TODO add your handling code here:
        if (jComboBoxModifier1.getItemCount()!=0){
            Sommet sommet1 = graphe.getSommets().get(jComboBoxModifier1.getSelectedItem().toString());
            Sommet sommet2 = graphe.getSommets().get(jComboBoxModifier2.getSelectedItem().toString());
            Lien lien = null;

            for (Lien l : graphe.getLiens()) {
                if ((l.getSommet1() == sommet1 && l.getSommet2() == sommet2) ||
                        (l.getSommet1() == sommet2 && l.getSommet2() == sommet1)) {
                    lien = l;
                    break;
                }
            }

            if (lien != null) {
                double duree = lien.getDureeMoyenne();
                double distance = lien.getDistance();
                double fiabilite = lien.getFiabilite();


                jTextFieldDuree.setText(String.valueOf(duree));
                jTextFieldDistance.setText(String.valueOf(distance));
                jTextFieldFiabilite.setText(String.valueOf(fiabilite));

                jTextFieldDuree.setEditable(true);
                jTextFieldDistance.setEditable(true);
                jTextFieldFiabilite.setEditable(true);
            } else {
                jTextFieldDuree.setText("");
                jTextFieldDistance.setText("");
                jTextFieldFiabilite.setText("");
            }



        }else JOptionPane.showMessageDialog(this, "Centre non trouvé", "Erreur", JOptionPane.ERROR_MESSAGE);
        
        
        
        
    }//GEN-LAST:event_jButtonModifierOkActionPerformed

    private void jButtonModifierQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierQuitterActionPerformed
        // TODO add your handling code here:
        jDialogModifierLien.setVisible(false);
    }//GEN-LAST:event_jButtonModifierQuitterActionPerformed

    private void jMenuTrajetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrajetActionPerformed
        // menu trajet
        jTextFieldTrajetFiabilite.setText("");
        jListTrajet.setModel(listModelListTrajetRisque);
        listModelListTrajetRisque.clear();
        
        jDialogRisque.setSize(470,700);
        jDialogRisque.setLocationRelativeTo(this);
        jDialogRisque.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuTrajetActionPerformed

    private void jButtonTrajetQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrajetQuitterActionPerformed
        // TODO add your handling code here:*
        jDialogRisque.setVisible(false);
    }//GEN-LAST:event_jButtonTrajetQuitterActionPerformed

    private void jButtonTrajetOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrajetOkActionPerformed
        // TODO add your handling code here:
        try{
            double fiab = Double.parseDouble(jTextFieldTrajetFiabilite.getText());
            if (fiab<0 || fiab>100){
                JOptionPane.showMessageDialog(this, "La fiabilité doit être entre 0 et 100", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            fiab=fiab/10;
            listModelListTrajetRisque.clear();

            for (Lien l : graphe.getLiens()) {
                if (l.getFiabilite()>=fiab){
                    listModelListTrajetRisque.addElement(l.getSommet1().getNom()+" ("+l.getSommet1().getType()+      ") - "+l.getSommet2().getNom() + " (" + l.getSommet2().getType() +") | "+  graphe.getLienEntreCentres(l.getSommet1().getNom(),l.getSommet2().getNom()).getFiabilite()*10 +"%"     );
                }
            }
            
            
            
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Les valeurs doivent être des doubles", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        
        
        
        
    }//GEN-LAST:event_jButtonTrajetOkActionPerformed
    

    
    private void ouvrirMessageInfo() {
        JOptionPane.showMessageDialog(this, "N'oubliez pas de charger le graphe d'abord !");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }
    
    private void effacerDonneeLister(){
       listModelListMaternite.clear();
       listModelListNutrition.clear();
       listModelListOperation.clear();
       jLabelNbrMaternite.setText("");
       jLabelNbrNutrition.setText("");
       jLabelNbrOperatoire.setText("");
       jLabelNbrTotal.setText("");
    }
    

    private void effacerDonneeComparateur(){
        jLabelNbM1.setText("");
        jLabelNbM2.setText("");
        jLabelNbN1.setText("");
        jLabelNbN2.setText("");
        jLabelNbO1.setText("");
        jLabelNbO2.setText("");
    }
    
    private void viderCheminCentre2(){
        if (jComboBoxChemin2.getItemCount()!=0){
            jComboBoxChemin2.removeAllItems();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonCentre1;
    private javax.swing.JButton jButtonCheminOk;
    private javax.swing.JButton jButtonCheminQuitter;
    private javax.swing.JButton jButtonConfirmerChangement;
    private javax.swing.JButton jButtonListerOk;
    private javax.swing.JButton jButtonModifierOk;
    private javax.swing.JButton jButtonModifierQuitter;
    private javax.swing.JButton jButtonOkComparateur;
    private javax.swing.JButton jButtonOkVoisin;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonQuitterComparateur;
    private javax.swing.JButton jButtonQuitterVoisin;
    private javax.swing.JButton jButtonTrajetOk;
    private javax.swing.JButton jButtonTrajetQuitter;
    private javax.swing.JComboBox<String> jComboBoxCentre1;
    private javax.swing.JComboBox<String> jComboBoxCentre2;
    private javax.swing.JComboBox<String> jComboBoxChemin1;
    private javax.swing.JComboBox<String> jComboBoxChemin2;
    private javax.swing.JComboBox<String> jComboBoxChoix;
    private javax.swing.JComboBox<String> jComboBoxModifier1;
    private javax.swing.JComboBox<String> jComboBoxModifier2;
    private javax.swing.JComboBox<String> jComboBoxOption;
    private javax.swing.JComboBox<String> jComboBoxVoisinage;
    private javax.swing.JDialog jDialogChemin;
    private javax.swing.JDialog jDialogComparateur;
    private javax.swing.JDialog jDialogListerNoeud;
    private javax.swing.JDialog jDialogModifierLien;
    private javax.swing.JDialog jDialogRisque;
    private javax.swing.JDialog jDialogVoisinage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNbM1;
    private javax.swing.JLabel jLabelNbM2;
    private javax.swing.JLabel jLabelNbN1;
    private javax.swing.JLabel jLabelNbN2;
    private javax.swing.JLabel jLabelNbO1;
    private javax.swing.JLabel jLabelNbO2;
    private javax.swing.JLabel jLabelNbrMaternite;
    private javax.swing.JLabel jLabelNbrNoeud;
    private javax.swing.JLabel jLabelNbrNutrition;
    private javax.swing.JLabel jLabelNbrOperatoire;
    private javax.swing.JLabel jLabelNbrTotal;
    private javax.swing.JList<String> jListCentreVoisin;
    private javax.swing.JList<String> jListChemin;
    private javax.swing.JList<String> jListChoixType;
    private javax.swing.JList<String> jListMaternite;
    private javax.swing.JList<String> jListNutrition;
    private javax.swing.JList<String> jListOperatoire;
    private javax.swing.JList<String> jListTrajet;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCharger;
    private javax.swing.JMenuItem jMenuItemAfficherVoisinage;
    private javax.swing.JMenuItem jMenuItemChemin;
    private javax.swing.JMenuItem jMenuItemComparateur;
    private javax.swing.JMenuItem jMenuItemListerNoeud;
    private javax.swing.JMenuItem jMenuItemModifierLien;
    private javax.swing.JMenuItem jMenuTrajet;
    private javax.swing.JRadioButton jRadioButtonDistance1;
    private javax.swing.JRadioButton jRadioButtonDistance2;
    private javax.swing.JRadioButton jRadioButtonTous;
    private javax.swing.JRadioButton jRadioButtonTypeDonne;
    private javax.swing.JRadioButton jRadioButtonVoisinageM;
    private javax.swing.JRadioButton jRadioButtonVoisinageN;
    private javax.swing.JRadioButton jRadioButtonVoisinageO;
    private javax.swing.JRadioButton jRadioButtonVoisinageTous;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldDistance;
    private javax.swing.JTextField jTextFieldDuree;
    private javax.swing.JTextField jTextFieldFiabilite;
    private javax.swing.JTextField jTextFieldTrajetFiabilite;
    private javax.swing.JTextField jTextFieldVoisinageNbr;
    // End of variables declaration//GEN-END:variables
}
